version: '3'

services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    ports:
      - 80:3000
    command: sh -c "npm run dev"
    env_file:
      - docker/web/.env
    volumes:
      - ./web:/app
    tty: true